const SUPABASE_URL = "https://cmneviikjxrjxqsvektg.supabase.co"; 
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtbmV2aWlranhyanhxc3Zla3RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzOTcxNjcsImV4cCI6MjA3Nzk3MzE2N30.GScLcmiZuzEGxKvsFepJTDMi8D33D9MNi6za4RPdebo
